import type { TeamMember, Rock, Task, EODReport } from "./types"

export const initialTeamMembers: TeamMember[] = [
  {
    id: "adam-wolfe",
    name: "Adam Wolfe",
    email: "adam@aims.com",
    role: "admin",
    department: "Leadership",
    weeklyMeasurable: "# of leads, MRR, playbooks, tools for MP, MA, & Others",
    joinDate: "2023-01-01",
  },
  {
    id: "kumar-sahil",
    name: "Kumar Sahil",
    email: "kumar@aims.com",
    role: "member",
    department: "Automation",
    weeklyMeasurable: "# of workflows automated (kanban)",
    joinDate: "2023-02-15",
  },
  {
    id: "maureen-maingi",
    name: "Maureen Maingi",
    email: "maureen@aims.com",
    role: "member",
    department: "Analytics",
    weeklyMeasurable: "# of dashboards/reports delivered",
    joinDate: "2023-03-01",
  },
  {
    id: "sheenam-seo",
    name: "Sheenam Seo",
    email: "sheenam@aims.com",
    role: "member",
    department: "Marketing",
    weeklyMeasurable: "# of SEO deliverables & clients managed w/ positive ROI",
    joinDate: "2023-04-10",
  },
  {
    id: "irtaza-naqvi",
    name: "Irtaza Naqvi",
    email: "irtaza@aims.com",
    role: "member",
    department: "Technology",
    weeklyMeasurable: "# of GHL snapshots made & clients managed w/ positive ROI",
    joinDate: "2023-05-20",
  },
  {
    id: "saad-ahmed",
    name: "Saad Ahmed",
    email: "saad@aims.com",
    role: "member",
    department: "Sales",
    weeklyMeasurable: "# of leads created for client campaigns",
    joinDate: "2023-06-01",
  },
]

export const initialRocks: Rock[] = [
  // Adam Wolfe's Rocks
  {
    id: "adam-r1",
    userId: "adam-wolfe",
    title: "AIMS Client Acquisition & Fulfillment",
    description: "3+ new AIMS clients closed and successfully onboarded with measurable results",
    bucket: "Client Fulfillment",
    outcome: "3+ new AIMS clients closed and successfully onboarded with measurable results",
    doneWhen: [
      "3+ new clients signed at $5K+ MRR each",
      "Each client onboarded within 14 days",
      "All clients have defined success metrics and weekly reporting",
      "Team delivering without Adam in day-to-day execution",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },
  {
    id: "adam-r2",
    userId: "adam-wolfe",
    title: "Revenue Intelligence Dashboard",
    description: "Single source of truth for all revenue metrics adopted in L10s before Matt Miller starts",
    bucket: "RevOps/CRM",
    outcome: "Single source of truth for all revenue metrics adopted in L10s before Matt Miller starts",
    doneWhen: [
      "Dashboard live: Leads → Booked → Show → Close → Revenue → CAC → LTV",
      "<5% data discrepancy between CRM, marketing, and finance",
      "100% adoption as official L10 scorecard source",
      "Attribution working: know where every lead came from",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },
  {
    id: "adam-r3",
    userId: "adam-wolfe",
    title: "Productize 3 AIMS Offers",
    description: "3 packaged, repeatable offers ready to sell to multiple clients",
    bucket: "New Playbooks",
    outcome: "3 packaged, repeatable offers ready to sell to multiple clients",
    doneWhen: [
      "Revenue Intelligence OS documented with scope, pricing, delivery SOP",
      "Voice Agent Playbook documented with scope, pricing, delivery SOP",
      "SEO/AEO Service packaged with defined deliverables and price",
      "Each offer has sales collateral and case study",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },
  {
    id: "adam-r4",
    userId: "adam-wolfe",
    title: "CRM Infrastructure Ready for Matt Miller",
    description: "HubSpot/CRM foundation complete before Feb 1 handoff",
    bucket: "RevOps/CRM",
    outcome: "HubSpot/CRM foundation complete before Feb 1 handoff",
    doneWhen: [
      "Pipeline stages and rules defined",
      "Lead attribution tracking working",
      "Integration between forms, CRMs, dialers complete",
      "Documentation ready for Matt Miller handoff",
    ],
    progress: 0,
    dueDate: "2025-02-01",
    status: "on-track",
    createdAt: "2025-01-01",
  },

  // Kumar Sahil's Rocks
  {
    id: "kumar-r1",
    userId: "kumar-sahil",
    title: "Deploy 15 Production Automations",
    description: "15+ automations live serving clients and internal operations",
    bucket: "Ops/Automation",
    outcome: "15+ automations live serving clients and internal operations",
    doneWhen: [
      "15+ automations deployed to production",
      "Automation kanban active and visible",
      "Each automation has owner, documentation, and error handling",
      "5 deployed by Jan 31, 10 by Feb 28, 15 by Mar 31",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },
  {
    id: "kumar-r2",
    userId: "kumar-sahil",
    title: "Lead Gen Automation System for Saad",
    description: "Automated system enabling 50K+ leads/week without manual effort",
    bucket: "Ops/Automation",
    outcome: "Automated system enabling 50K+ leads/week without manual effort",
    doneWhen: [
      "4+ lead gen workflows live",
      "Saad independently generates 50K+ leads/week using system",
      "Manual lead gen effort reduced by 50%+",
      "List replenishment alerts working",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },
  {
    id: "kumar-r3",
    userId: "kumar-sahil",
    title: "Client Reporting Automation",
    description: "Automated reporting reducing manual report creation by 70%+",
    bucket: "Ops/Automation",
    outcome: "Automated reporting reducing manual report creation by 70%+",
    doneWhen: [
      "Automated data pulls from Instantly, GHL, GA4",
      "Report generation workflow live",
      "Weekly client reports auto-generated",
      "Time savings documented",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },
  {
    id: "kumar-r4",
    userId: "kumar-sahil",
    title: "Cross-Company Data Integrations",
    description: "3 integrations eliminating manual data handoffs across VP/VendHub/MA/AIMS",
    bucket: "Ops/Automation",
    outcome: "3 integrations eliminating manual data handoffs across VP/VendHub/MA/AIMS",
    doneWhen: [
      "Data flow map complete across all 4 companies",
      "3 highest-impact integrations live",
      "Manual handoffs eliminated for those flows",
      "Zero critical sync failures",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },

  // Maureen Maingi's Rocks
  {
    id: "maureen-r1",
    userId: "maureen-maingi",
    title: "Client Dashboard Delivery",
    description: "All active clients have live dashboards with defined reporting cadence",
    bucket: "Client Fulfillment",
    outcome: "All active clients have live dashboards with defined reporting cadence",
    doneWhen: [
      "Concierge Auctions dashboard live with weekly reporting",
      "McKenzie SewOn dashboard live with weekly reporting",
      "MedPros dashboard live with weekly reporting",
      "Modern Amenities dashboard live with weekly reporting",
      "Each dashboard has owner and update cadence documented",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },
  {
    id: "maureen-r2",
    userId: "maureen-maingi",
    title: "L10 Revenue Intelligence Dashboard",
    description: "Single source of truth adopted by leadership for L10 meetings",
    bucket: "RevOps/CRM",
    outcome: "Single source of truth adopted by leadership for L10 meetings",
    doneWhen: [
      "Dashboard live: Leads → Booked → Show → Close → Revenue → CAC → LTV",
      "Data reconciled to <5% discrepancy",
      "100% L10 adoption",
      "Weekly refresh automated or documented",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },
  {
    id: "maureen-r3",
    userId: "maureen-maingi",
    title: "Sales Performance Analytics",
    description: "Close rate and show rate drivers identified with actionable recommendations",
    bucket: "RevOps/CRM",
    outcome: "Close rate and show rate drivers identified with actionable recommendations",
    doneWhen: [
      "Close rate driver analysis complete with top 5 drivers identified",
      "Show rate baseline established and tracked weekly",
      "Rep-level and source-level benchmarks created",
      "Recommendations presented to sales leadership",
      "Weekly sales performance report delivered consistently",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },

  // Sheenam Seo's Rocks
  {
    id: "sheenam-r1",
    userId: "sheenam-seo",
    title: "Weekly SEO Deliverable Production",
    description: "Consistent weekly SEO deliverables across all managed clients",
    bucket: "Client Fulfillment",
    outcome: "Consistent weekly SEO deliverables across all managed clients",
    doneWhen: [
      "SEO deliverable types defined and tracked",
      "Weekly production targets set per client",
      "Deliverables tracked in kanban/spreadsheet",
      "Monthly client reports delivered by 5th of each month",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },
  {
    id: "sheenam-r2",
    userId: "sheenam-seo",
    title: "Client Traffic Growth & ROI",
    description: "Measurable traffic growth and positive ROI for all SEO clients",
    bucket: "Client Fulfillment",
    outcome: "Measurable traffic growth and positive ROI for all SEO clients",
    doneWhen: [
      "Traffic baselines documented per client",
      "MA organic traffic +40% QoQ",
      "VP organic traffic +50% QoQ",
      "Positive ROI demonstrated for all clients",
      "Monthly ROI reporting delivered",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },
  {
    id: "sheenam-r3",
    userId: "sheenam-seo",
    title: "Keyword Ranking Performance",
    description: "Priority keywords ranking in top 3 positions",
    bucket: "Client Fulfillment",
    outcome: "Priority keywords ranking in top 3 positions",
    doneWhen: [
      "Priority keyword list defined per client",
      "Current rankings baselined",
      "Target keywords moved to top 3 by Q1 end",
      "Weekly ranking tracking maintained",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },
  {
    id: "sheenam-r4",
    userId: "sheenam-seo",
    title: "SEO/AEO Playbook Documentation",
    description: "SEO/AEO service packaged as repeatable productized offer",
    bucket: "New Playbooks",
    outcome: "SEO/AEO service packaged as repeatable productized offer",
    doneWhen: [
      "Service scope defined with pricing",
      "Delivery SOP written",
      "Backlink acquisition process documented",
      "Schema/AEO implementation process documented",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },

  // Irtaza Naqvi's Rocks
  {
    id: "irtaza-r1",
    userId: "irtaza-naqvi",
    title: "GHL Snapshot Library",
    description: "4 production-ready snapshots for rapid client deployment",
    bucket: "New Playbooks",
    outcome: "4 production-ready snapshots for rapid client deployment",
    doneWhen: [
      "AIMS Core Snapshot live with 3 pipelines and 15+ automations",
      "Voice Dialer Snapshot live",
      "Lead Gen Snapshot live",
      "VP Subaccount Snapshot live",
      "All snapshots documented and cloned to Cursive GHL",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },
  {
    id: "irtaza-r2",
    userId: "irtaza-naqvi",
    title: "Client GHL Management & ROI",
    description: "All GHL clients managed with measurable positive ROI",
    bucket: "Client Fulfillment",
    outcome: "All GHL clients managed with measurable positive ROI",
    doneWhen: [
      "ROI defined and tracked for each client",
      "MedPros deployed and generating results",
      "MA deployed and generating results",
      "New AIMS clients deployed within 48 hours",
      "Weekly client health report delivered",
      "Zero churn due to GHL issues",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },
  {
    id: "irtaza-r3",
    userId: "irtaza-naqvi",
    title: "Voice Dialer Deployment",
    description: "Voice dialers live and generating qualified conversations",
    bucket: "Client Fulfillment",
    outcome: "Voice dialers live and generating qualified conversations",
    doneWhen: [
      "MedPros dialer live",
      "MA dialer live",
      "2+ dialers generating qualified conversations",
      "Weekly performance reporting active",
      "Positive ROI demonstrated per dialer",
      "Voice Agent Playbook documented",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },
  {
    id: "irtaza-r4",
    userId: "irtaza-naqvi",
    title: "VP Subaccount Scale Prep",
    description: "VP subaccount template validated and ready for 1,500 members",
    bucket: "New Playbooks",
    outcome: "VP subaccount template validated and ready for 1,500 members",
    doneWhen: [
      "3 pilot accounts deployed",
      "Feedback collected and incorporated",
      "Template validated",
      "Scale deployment plan documented",
      "Support model defined for 1,500 members",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },

  // Saad Ahmed's Rocks
  {
    id: "saad-r1",
    userId: "saad-ahmed",
    title: "Lead Volume Production",
    description: "50K+ leads per week delivered to all active client campaigns",
    bucket: "Client Fulfillment",
    outcome: "50K+ leads per week delivered to all active client campaigns",
    doneWhen: [
      "50K+ leads produced weekly",
      "Bounce rate <1%",
      "No campaign paused due to lead shortage",
      "Weekly production tracked and reported",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },
  {
    id: "saad-r2",
    userId: "saad-ahmed",
    title: "Lead Quality & Enrichment",
    description: "High-quality enriched leads driving 3%+ reply rates",
    bucket: "Client Fulfillment",
    outcome: "High-quality enriched leads driving 3%+ reply rates",
    doneWhen: [
      "Quality scoring implemented",
      "Enrichment workflows live",
      "3%+ reply rate achieved across campaigns",
      "20%+ low-quality leads filtered pre-send",
      "Quality improving month-over-month",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },
  {
    id: "saad-r3",
    userId: "saad-ahmed",
    title: "Campaign-Specific Lead Flows",
    description: "Each client campaign has dedicated ICP workflow",
    bucket: "Client Fulfillment",
    outcome: "Each client campaign has dedicated ICP workflow",
    doneWhen: [
      "Concierge Auctions ICP workflow live",
      "McKenzie SewOn ICP workflow live",
      "MA B2B ICP workflow live",
      "Weekly delivery targets met per campaign",
      "Performance tracked by campaign",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },
  {
    id: "saad-r4",
    userId: "saad-ahmed",
    title: "Lead Gen Cost Optimization",
    description: "20-30% reduction in tool costs while maintaining volume",
    bucket: "Ops/Automation",
    outcome: "20-30% reduction in tool costs while maintaining volume",
    doneWhen: [
      "Tool stack audited",
      "Unused tools cancelled",
      "Cost per lead reduced 20-30%",
      "50K+/week volume maintained",
      "Optimized stack documented",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },
  {
    id: "saad-r5",
    userId: "saad-ahmed",
    title: "Lead Gen SOPs",
    description: "Complete documentation enabling anyone to run lead gen",
    bucket: "Ops/Automation",
    outcome: "Complete documentation enabling anyone to run lead gen",
    doneWhen: [
      "Data sourcing SOP complete",
      "List building SOP complete",
      "Enrichment SOP complete",
      "Delivery SOP complete",
      "Documentation tested with unfamiliar team member",
    ],
    progress: 0,
    dueDate: "2025-03-31",
    status: "on-track",
    createdAt: "2025-01-01",
  },
]

export const initialTasks: Task[] = []

export const initialEODReports: EODReport[] = []
